### PR TITLE
Fix bug where offline warning message was not shown in the AppBar.

### LINKED ISSUE #32: Offline warning not show in AppBar when in offline mode
# Bug report

## Describe the bug

`<AppBar offlineWarning="some message"/>` should display that message when the user is offline.  It currently does not.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Put browser in offline mode using dev tools
2. The offline warning will not show

## Expected behavior

The offline warning message should be displayed in the AppBar

### PR DESCRIPTION
**Pull request by markbrocato**
Fixes #32 

Also, removes our internal handling of the scroll event to show and hide the AppBar in favor of `useScrollTrigger` as suggested [here](https://material-ui.com/components/app-bar/#hide-app-bar).

### CODE REVIEW

File: src/AppBar.js [hunk 1]
```diff
@@ -1,179 +1,84 @@
...
+      <Toolbar disableGutters className={classes.toolbar}>
+        {children}
+      </Toolbar>
+    </MUIAppBar>
+  )
 
-    lastScrollY.current = scrollY
+  if (!fixed) {
+    appBar = (
+      <Slide appear={false} direction="down" in={!trigger}>
```
Comment (leotoll) [inline src/AppBar.js]:
```suggestion
      <Slide in={!trigger}>
```
